import type { StatusCode, StatusName, StatusPhrase } from "./consts";
import { httpStatus } from "./status";

/**
 * Factory methods and type guards generated by {@link AppError.define}.
 *
 * The factory provides a type-safe API for creating, throwing, and checking
 * {@link AppError} instances from application-specific error code mappings.
 *
 * @template T The union of application-specific error code strings.
 *
 * @see {@link AppError}
 *
 * @example
 * ```ts
 * const errors = AppError.define({
 *   userNotFound: "NotFound",
 *   invalidInput: "BadRequest",
 * });
 *
 * errors.throw("userNotFound", "User does not exist");
 * ```
 */
export interface AppErrorFactory<T extends string> {
  /**
   * Creates an {@link AppError} instance without throwing it.
   *
   * @param code Application-specific error code.
   * @param message Human-readable error message.
   * @param cause Optional underlying error or additional failure context.
   * @returns A new {@link AppError} instance.
   *
   * @example
   * ```ts
   * const error = errors.create(
   *   "userNotFound",
   *   "User does not exist",
   * );
   * ```
   */
  create: (code: T, message: string, cause?: unknown) => AppError<T>;

  /**
   * Creates and immediately throws an {@link AppError} instance.
   *
   * @param code Application-specific error code.
   * @param message Human-readable error message.
   * @param cause Optional underlying error or additional failure context.
   *
   * @throws {AppError} Always throws the created application error.
   *
   * @example
   * ```ts
   * errors.throw(
   *   "userNotFound",
   *   "User does not exist",
   * );
   * ```
   */
  throw: (code: T, message: string, cause?: unknown) => never;

  /**
   * Checks whether an unknown value is an {@link AppError} instance.
   *
   * This type guard narrows the value to `AppError<T>` when it returns `true`.
   *
   * @param err Value to check.
   * @returns `true` if the value is an {@link AppError} instance.
   *
   * @example
   * ```ts
   * if (errors.is(error)) {
   *   error.errorCode;
   * }
   * ```
   */
  is: (err: unknown) => err is AppError<T>;
}

/**
 * A structured application error containing an application-specific error code,
 * an HTTP status code, a status name, a reason phrase, and an optional cause.
 *
 * Instances should be created through {@link AppError.define} to ensure
 * consistent error construction and type-safe error codes.
 *
 * @template T The union of application-specific error code strings.
 *
 * @see {@link AppErrorFactory}
 *
 * @example
 * ```ts
 * const errors = AppError.define({
 *   userNotFound: "NotFound",
 * });
 *
 * const error = errors.create(
 *   "userNotFound",
 *   "User does not exist",
 * );
 * ```
 */
export class AppError<T extends string> extends Error {
  /**
   * The error name identifier.
   *
   * Always equal to `"AppError"`.
   */
  override readonly name = "AppError";

  /**
   * Application-specific error code.
   */
  readonly errorCode: T;

  /**
   * Numeric HTTP status code associated with this error.
   */
  readonly statusCode: StatusCode;

  /**
   * HTTP status name associated with this error.
   */
  readonly statusName: StatusName;

  /**
   * Human-readable HTTP status phrase associated with this error.
   */
  readonly statusPhrase: StatusPhrase;

  /**
   * Creates a new application error.
   *
   * This constructor is protected. Use {@link AppError.define} instead.
   *
   * @param errorCode Application-specific error code.
   * @param statusCode Numeric HTTP status code.
   * @param message Human-readable error message.
   * @param cause Optional underlying error or additional failure context.
   */
  protected constructor(errorCode: T, statusCode: StatusCode, message: string, cause?: unknown) {
    super(message);
    this.cause = cause;
    this.errorCode = errorCode;
    this.statusCode = statusCode;
    this.statusName = httpStatus.nameFromCode(statusCode);
    this.statusPhrase = httpStatus.phraseFromCode(statusCode);
  }

  /**
   * Converts this error into a plain serializable object.
   *
   * The returned object is suitable for HTTP responses, structured logging,
   * and JSON serialization.
   *
   * @returns A plain object containing the error code, HTTP status name,
   * message, and original cause.
   *
   * @example
   * ```ts
   * error.serialize();
   * // {
   * //   errorCode: "userNotFound",
   * //   httpStatus: "NotFound",
   * //   message: "User does not exist",
   * //   details: undefined
   * // }
   * ```
   */
  serialize(): {
    errorCode: string;
    httpStatus: StatusName;
    message: string;
    details: unknown;
  } {
    return {
      errorCode: this.errorCode,
      httpStatus: this.statusName,
      message: this.message,
      details: this.cause,
    };
  }

  /**
   * Creates a type-safe set of error factory functions from an error mapping.
   *
   * Each key in the mapping becomes an application-specific error code, and
   * each value defines the associated HTTP status name.
   *
   * @template E Union of application error codes inferred from the mapping keys.
   *
   * @param mapping Object mapping application error codes to HTTP status names.
   *
   * @returns An {@link AppErrorFactory} containing methods for creating,
   * throwing, and checking application errors.
   *
   * @example
   * ```ts
   * const errors = AppError.define({
   *   userNotFound: "NotFound",
   *   invalidInput: "BadRequest",
   * });
   *
   * errors.throw(
   *   "userNotFound",
   *   "User does not exist",
   * );
   *
   * const error = errors.create(
   *   "invalidInput",
   *   "Email is required",
   * );
   *
   * if (errors.is(error)) {
   *   error.statusCode;
   * }
   * ```
   */
  static define<E extends string>(mapping: Record<E, StatusName>): AppErrorFactory<E> {
    function create(errorCode: E, message: string, cause?: unknown): AppError<E> {
      return new AppError(errorCode, httpStatus.codeFromName(mapping[errorCode]), message, cause);
    }

    return {
      create,

      throw: (errorCode: E, message: string, cause?: unknown): never => {
        throw create(errorCode, message, cause);
      },

      is: (err: unknown): err is AppError<E> => err instanceof AppError,
    };
  }
}
