import { getReasonPhrase, StatusCodes } from "http-status-codes";

/**
 * Union of all valid HTTP status code names exposed by `http-status-codes`.
 *
 * Used to constrain the values in a `defineErrors` mapping so only real
 * status names (e.g. `"BAD_REQUEST"`, `"NOT_FOUND"`) are accepted.
 */
type StatusName = keyof typeof StatusCodes;

/**
 * A suite of type-safe error factory methods and type guards returned by `AppError.define`.
 *
 * @template T - Union of application-specific error code strings.
 */
export interface AppErrorFactory<T extends string> {
  /**
   * Creates an `AppError` without throwing it.
   *
   * @param code    One of the error codes defined in the mapping.
   * @param message Human-readable error message.
   * @param cause   Optional underlying cause.
   * @returns       A new `AppError` instance.
   */
  create: (code: T, message: string, cause?: unknown) => AppError<T>;

  /**
   * Creates and immediately throws an `AppError`.
   *
   * @param code    One of the error codes defined in the mapping.
   * @param message Human-readable error message.
   * @param cause   Optional underlying cause.
   * @returns       Never — always throws.
   */
  throw: (code: T, message: string, cause?: unknown) => never;

  /**
   * Type guard that narrows an unknown value to `AppError<T>`.
   *
   * @param err Any value to check.
   * @returns   `true` if `err` is an `AppError` instance.
   */
  is: (err: unknown) => err is AppError<T>;
}

/**
 * A structured application error carrying a custom error code,
 * an HTTP status code, and an optional cause.
 *
 * Instantiation via `new AppError()` is protected to enforce consistent error management.
 * Use `AppError.define()` as the primary entry point to generate type-safe factories.
 *
 * @template T - String literal union of your application's error codes.
 *
 * @example
 * ```typescript
 * const errors = AppError.define({
 *   USER_NOT_FOUND: "NOT_FOUND",
 * });
 *
 * // Create or throw using defined factory helpers:
 * errors.throw("USER_NOT_FOUND", "User does not exist");
 * const err = errors.create("USER_NOT_FOUND", "User does not exist");
 * ```
 */
export class AppError<T extends string> extends Error {
  /** Always `"AppError"` — useful for quick `error.name` checks. */
  override readonly name = "AppError";

  /** The application-specific error code (e.g. `"USER_NOT_FOUND"`). */
  readonly code: T;

  /** Numeric HTTP status code (e.g. `404`). */
  readonly statusCode: number;

  /** Human-readable HTTP status phrase (e.g. `"Not Found"`). */
  readonly status: string;

  /**
   * Protected constructor to prevent direct instantiation with `new AppError()`.
   * Use factory methods generated by `AppError.define()` instead.
   */
  protected constructor(code: T, statusCode: number, message: string, cause?: unknown) {
    super(message);
    this.cause = cause;
    this.code = code;
    this.statusCode = statusCode;
    this.status = getReasonPhrase(this.statusCode);
  }

  /**
   * Returns a plain object representation of the error, suitable
   * for JSON responses or logging.
   *
   * @returns A JSON object suitable for HTTP response
   */
  serialize(): { code: string; message: string; details: unknown } {
    return {
      code: this.code,
      message: this.message,
      details: this.cause,
    };
  }

  /**
   * Creates a suite of error factory functions (`create`, `throw`) and a type guard (`is`)
   * from a mapping of application error codes to HTTP status names.
   *
   * Define the mapping once, then use the returned helpers everywhere —
   * you get full type-safety on error codes and never have to remember
   * which numeric status goes with which code.
   *
   * @template E - String literal union derived from the mapping keys.
   * @param mapping - An object whose keys are your error codes and whose
   *                  values are HTTP status names (e.g. `"NOT_FOUND"`).
   * @returns An object with `create`, `throw`, and `is` methods.
   *
   * @example
   * ```typescript
   * const errors = AppError.define({
   *   USER_NOT_FOUND: "NOT_FOUND",
   *   INVALID_INPUT: "BAD_REQUEST",
   * });
   *
   * // throws an AppError — return type is `never`
   * errors.throw("USER_NOT_FOUND", "No user with that id");
   *
   * // creates an AppError without throwing
   * const err = errors.create("INVALID_INPUT", "Email is required");
   *
   * // type guard — narrows to AppError<"USER_NOT_FOUND" | "INVALID_INPUT">
   * if (errors.is(someError)) { ... }
   * ```
   */
  static define<E extends string>(mapping: Record<E, StatusName>): AppErrorFactory<E> {
    function create(code: E, message: string, cause?: unknown): AppError<E> {
      return new AppError(code, StatusCodes[mapping[code]], message, cause);
    }

    return {
      create,
      throw: (code: E, message: string, cause?: unknown): never => {
        throw create(code, message, cause);
      },
      is: (err: unknown): err is AppError<E> => err instanceof AppError,
    };
  }
}
