[tools]
biome = "2.5.10"
bun = "1.4.0"
cocogitto = "7.0.0"
lefthook = "2.1.11"
node = "26.8.1"
"npm:jsr" = "0.14.3"

[env]
_.path = ["./node_modules/.bin"]

[settings]
disable_backends = ["asdf"]
use_versions_host = false
minimum_release_age = "1d"

[tasks.lint]
description = "Check files with biome"
run = "biome check --diagnostic-level=warn --no-errors-on-unmatched"
[tasks.lint-fix]
description = "Fix files with biome"
run = "biome check --diagnostic-level=warn --no-errors-on-unmatched --write"
[tasks.typecheck]
description = "Run tsc"
run = "tsc"
[tasks.test]
description = "Run tests"
run = "bun test --coverage"
[tasks.test-staged]
description = "Run tests on staged files"
run = "bun test --changed --bail --reporter=dots"
[tasks.test-ci]
description = "Run tests in ci mode"
run = "bun test --bail --reporter=dots"
[tasks.publish-app-error]
description = "Build and publishes @mkvlrn/app-error to npm and jsr"
run = """
echo "Clean..."
rm -rf packages/app-error/dist

echo "Building @mkvlrn/app-error..."
bun build ./packages/app-error/src/main.ts --outdir ./packages/app-error/dist
tsc --declaration --emitDeclarationOnly --outDir packages/app-error/dist --module ESNext --moduleResolution Bundler packages/app-error/src/main.ts --ignoreConfig

echo "Publishing @mkvlrn/app-error to npm..."
(cd packages/app-error && npm publish --access public)

echo "Publishing @mkvlrn/app-error to jsr..."
(cd packages/app-error && jsr publish)
"""
[tasks.publish-config]
description = "Build and publishes @mkvlrn/config to npm and jsr"
run = """
echo "Clean..."
rm -rf packages/config/dist

echo "Building @mkvlrn/config..."
bunx typescript-json-schema ./packages/config/tsconfig.schema.json UserConfig --include './packages/config/node_modules/vitest/**/*.d.ts' > ./packages/config/vitest.schema.json

echo "Publishing @mkvlrn/config to npm..."
(cd packages/config && npm publish --access public)

echo "Publishing @mkvlrn/config to jsr..."
(cd packages/config && jsr publish)
"""
[tasks.publish-result]
description = "Build and publishes @mkvlrn/result to npm and jsr"
run = """
echo "Clean..."
rm -rf packages/result/dist

echo "Building @mkvlrn/result..."
bun build ./packages/result/src/main.ts --outdir ./packages/result/dist
tsc --declaration --emitDeclarationOnly --outDir packages/result/dist --module ESNext --moduleResolution Bundler packages/result/src/main.ts --ignoreConfig

echo "Publishing @mkvlrn/result to npm..."
(cd packages/result && npm publish --access public)

echo "Publishing @mkvlrn/result to jsr..."
(cd packages/result && jsr publish)
"""
[tasks.npm-dry-run]
description = "NPM publish dry run"
run = """
for dir in packages/*; do
  if [ -d "$dir" ]; then
    echo "Checking $dir"
    (cd "$dir" && bun publish --dry-run --access public --quiet)
  fi
done
"""
[tasks.jsr-dry-run]
description = "JSR publish dry run"
run = """
for dir in packages/*; do
  if [ -d "$dir" ]; then
    echo "Checking $dir"
    (cd "$dir" && jsr publish --dry-run --quiet --allow-dirty)
  fi
done
"""
[tasks.sync-branch]
description = "Sync package manager deps"
run = "mise install && mise prune -y && bun install --frozen-lockfile && lefthook install"
