name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4

      - name: Publish app-error
        if: startsWith(github.event.release.tag_name, 'app-error-v')
        working-directory: ./packages/app-error
        run: |
          bun install --production --ignore-scripts
          mise publish-app-error

      - name: Publish config
        if: startsWith(github.event.release.tag_name, 'config-v')
        working-directory: ./packages/config
        run: |
          bun install --ignore-scripts
          mise publish-config

      - name: Publish result
        if: startsWith(github.event.release.tag_name, 'result-v')
        working-directory: ./packages/result
        run: |
          mise publish-result
