name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4

      - name: Publish app-error to JSR
        if: startsWith(github.event.release.tag_name, 'app-error-v')
        working-directory: ./packages/app-error
        run: |
          bun install --production --ignore-scripts
          bunx jsr publish

      - name: Publish config to JSR
        if: startsWith(github.event.release.tag_name, 'config-v')
        working-directory: ./packages/config
        run: |
          bun install --ignore-scripts
          bunx jsr publish

      - name: Publish result to JSR
        if: startsWith(github.event.release.tag_name, 'result-v')
        working-directory: ./packages/result
        run: bunx jsr publish
